region = "ap-south-1" #Can choose any region
vpc-cidr = "10.0.0.0/16" #Can give your own cidr for vpc
public-subnet-cidr = "10.0.0.0/24"
public-subnet-az = "ap-south-1a" #Can choose any AZ
private-subnet-cidr = "10.0.1.0/24" 
private-subnet-az = "ap-south-1a"
ami = "your-ami" #The AMI id changes for different regions
instance-type = "t2.micro"
key-name = "key-pair" #Give your key-pair that is already there, create one if it does not exist